version: '3.4'

services:
  cryptocat-frontend:
    image: cryptocat-frontend
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
      - sub-etha
    ports:
      - 80:80
  cryptocat-backend:
    image: cryptocat-backend
    build: ../cryptocat-backend
    networks:
      - sub-etha

networks:
  sub-etha:
